Blue:
  lower:
  - 90
  - 100
  - 75
  upper:
  - 130
  - 255
  - 255
Green:
  lower:
  - 35
  - 70
  - 0
  upper:
  - 85
  - 255
  - 255
Orange:
  lower:
  - 5
  - 150
  - 160
  upper:
  - 15
  - 255
  - 255
Purple:
  lower:
  - 125
  - 50
  - 0
  upper:
  - 160
  - 255
  - 100
Red:
  lower:
  - 0
  - 100
  - 100
  upper:
  - 5
  - 255
  - 255
Yellow:
  lower:
  - 20
  - 100
  - 100
  upper:
  - 30
  - 255
  - 255
